### ISSUE TITLE
Next Version

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#132]
- [x] 框架依赖预打包依赖 @ClarkXia #77
- [x] #141
 - [x] eslint / tsChecker @ClarkXia #94
 - [ ] 运行时变量 process.env @imsobear #93 
 - [x] React 18 适配 @chenjun1011 #105
 - [x] SSR 构建产物调整 #108
 - [x] Route Wrapper  https://github.com/ice-lab/ice-next/pull/135

---

move to Next Version:
 - Mock #97 @luhc228 
 - 数据请求方案 @chenjun1011 #101
 - 文档 @luhc228 #124

**Comment by usercao** [comment]
希望升级react router v6

**Comment by imsobear** [comment]
> 希望升级react router v6

具体需要哪个特性

**Comment by usercao** [comment]
可以看一下这个 alibaba/ice#4917，好处有很多例如不用再写`exact: true,`就可以减少很多代码
