### ISSUE TITLE
Alpha 版本遗留问题

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/ice-next#81]
- [x] 约定式路由 defineRoutes 能力 #69 
- [x] SSR esbuild 处理 css module 样式问题 #43 
- [x] 页面组件能力优化，页面 scripts 和 links 能力 #74 
- [x] ~ice 主包变更和重构，移除内置插件 #67~
- [x] 目录规范 #115
- [x] dev 删除页面报错
- [x] appContext 优化 #84 #66
- [x] dev 阶段无法自动打开预览页面 #100
- [x] 端口占用 - 提示
- [x] #104
- [ ] #97
- [x] #94  tsChecker eslint 单独 PR
- [x] #88
- [x] #82
- [x] #71
- [x] defineUserConfig -> defineConfig

**Comment by chenjun1011** [comment]
修改代码后，SSR 的构建产物好像还是不会更新，需要重启 devServer

**Comment by chenjun1011** [comment]
现在每次 dev 启动的时候，自动打开的是包大小 analyze 的页面，而不是应用页面，这个是不是要优化下？

**Comment by luhc228** [comment]
dev 阶段，如果删除某个页面，会报错bi并直接退出进程：
![image](https://user-images.githubusercontent.com/44047106/162367071-b070af6c-221b-4d48-b133-ec47d197aec4.png)

**Comment by chenjun1011** [comment]
appContext 暴露哪些内容也需要确定下

**Comment by luhc228** [comment]
> dev 阶段，如果删除某个页面，会报错bi并直接退出进程：
> 
> <img alt="35689D66-6BE4-4690-A9EB-7F324F72C6CC" width="500" src="https://user-images.githubusercontent.com/44047106/162367345-f6a8006d-1985-4e80-aaf9-bf86596be17a.png">

https://github.com/ice-lab/ice-next/blob/67618a2d76c7e480af5d6b05ae53e3c504191b6b/packages/ice/src/getWatchEvents.ts#L31 

这里的改动会修复上面的问题

**Comment by usercao** [comment]
`端口占用 - 提示` 建议像vue-cli一样直接开新端口打开体验会好点，一般出现这种情况都不会关闭已占用端口，目的就是开新端口
